"""Builds icons.js (UI icon subset) and vendor/lucide-all.json (full searchable library) from lucide-static (ISC licence).
Usage: python3 tools/build_icons.py /path/to/lucide-static/package"""
import json, os, re, sys
pkg = sys.argv[1]
icons, tags = {}, json.load(open(os.path.join(pkg, 'tags.json')))
for f in sorted(os.listdir(os.path.join(pkg, 'icons'))):
    if f.endswith('.svg'):
        t = open(os.path.join(pkg, 'icons', f)).read()
        inner = re.sub(r'\s+', ' ', re.search(r'<svg[^>]*>(.*)</svg>', t, re.S).group(1)).strip().replace('> <', '><')
        icons[f[:-4]] = inner
UI = """layout-template printer shapes type image upload sparkles wand-sparkles file house undo-2 redo-2 search save folder-open shirt gem download chevron-down chevron-left chevron-right
rotate-cw ellipsis x check plus minus trash-2 copy lock lock-open layers arrow-up arrow-down chevrons-up chevrons-down flip-horizontal flip-vertical align-start-vertical align-center-vertical
align-end-vertical align-start-horizontal align-center-horizontal align-end-horizontal palette scissors zoom-in brush eraser tag crop sliders-horizontal contrast droplets pencil bold italic underline
align-left align-center align-right baseline frame smile star heart sticker square circle triangle hexagon coffee file-text smartphone presentation credit-card layout-grid cup-soda mouse package ticket
bookmark flag mail utensils award book-open gift newspaper video monitor tv instagram youtube facebook linkedin twitter folder files flame users dice-5 shuffle loader info triangle-alert arrow-left
settings key shield cloud sun moon camera link external-link images badge-check crown mic wand blend sparkle zap move maximize-2 hand mouse-pointer-click text-cursor-input pen-tool minus-circle
circle-check circle-x eye eye-off group ungroup sticker clapperboard box boxes shopping-bag shopping-cart store sprout leaf cake party-popper graduation-cap briefcase camera-off scan  droplet flip-vertical-2
ruler rotate-ccw clock list list-ordered paintbrush palette bell heart-handshake ribbon scroll-text receipt tent-tree  gamepad-2 music headphones plane map-pin globe cherry apple pizza wine beer ice-cream-cone
cake-slice gem layout-dashboard columns-2 rows-2 grid-2x2 panel-top app-window laptop tablet phone folder-plus file-plus file-down file-up undo redo case-sensitive baseline highlighter paint-bucket pipette
message-circle share-2 arrow-right arrow-up-right download-cloud wifi-off history wand-sparkles spline sparkles brain-circuit cpu scaling door-open pin hard-hat a-large-small""".split()
missing = [n for n in dict.fromkeys(UI) if n not in icons]
print('missing:', missing)
ui = {n: icons[n] for n in dict.fromkeys(UI) if n in icons}
js = "/* Generated by tools/build_icons.py from Lucide (ISC licence). */\nwindow.CHITRA_ICONS=" + json.dumps(ui, separators=(',', ':')) + ";\n" + r"""
window.ico = (n, s = 20, cls = '') => /^brand:/.test(n) && window.CHITRA_BRANDS && window.CHITRA_BRANDS[n.slice(6)] ? `<svg class="ic brand ${cls}" width="${s}" height="${s}" viewBox="0 0 24 24" fill="#${window.CHITRA_BRANDS[n.slice(6)].h}" aria-hidden="true"><path d="${window.CHITRA_BRANDS[n.slice(6)].p}"/></svg>` : (window.CHITRA_DUO && window.CHITRA_DUO[n]) ? `<svg class="ic duo ${cls}" width="${s}" height="${s}" viewBox="0 0 256 256" fill="currentColor" aria-hidden="true">${window.CHITRA_DUO[n]}</svg>` : `<svg class="ic ${cls}" width="${s}" height="${s}" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true">${window.CHITRA_ICONS[n] || ''}</svg>`;
window.hydrateIcons = (root = document) => root.querySelectorAll('[data-ico]').forEach(e => { if (!e.dataset.done) { e.innerHTML = window.ico(e.dataset.ico, +e.dataset.s || 20); e.dataset.done = 1; } });
document.addEventListener('DOMContentLoaded', () => window.hydrateIcons());
"""
open('icons.js', 'w').write(js)
os.makedirs('vendor', exist_ok=True)
json.dump({n: [icons[n], tags.get(n, [])] for n in icons}, open('vendor/lucide-all.json', 'w'), separators=(',', ':'))
print(len(ui), 'ui icons;', len(icons), 'library icons')
