#!/usr/bin/env node
/* Contact sheet of data/mockups/index.json: each real product photo with a sample design applied through its print-area quad. Look at it and fix quads.
   Usage: node tools/mockup-sheet.mjs out.png   (app served on :8123) */
import { createRequire } from 'node:module'; const require = createRequire(import.meta.url); const { chromium } = require('playwright');
const out = process.argv[2] || '/tmp/mockup-sheet.png', b = await chromium.launch(), p = await b.newPage({ viewport: { width: 1500, height: 900 } });
await p.route(/fonts\.(googleapis|gstatic)|jsdelivr|staticimgly/, r => r.abort()); await p.addInitScript(() => localStorage.setItem('chitra.tour', '1')); await p.goto((process.env.BASE || 'http://localhost:8123/') + '?nosplash'); await p.waitForTimeout(2000);
const urls = await p.evaluate(async () => { const idx = await (await fetch('data/mockups/index.json', { cache: 'no-store' })).json(), res = [];
  const art = document.createElement('canvas'); art.width = 1200; art.height = 800; const g = art.getContext('2d'), gr = g.createLinearGradient(0, 0, 1200, 800); gr.addColorStop(0, '#7c3aed'); gr.addColorStop(1, '#f472b6'); g.fillStyle = gr; g.fillRect(0, 0, 1200, 800); g.fillStyle = '#fff'; g.textAlign = 'center'; g.font = '800 170px sans-serif'; g.fillText('YOUR', 600, 380); g.fillText('DESIGN', 600, 560);
  for (const x of idx.mockups) { try { const im = new Image(); im.crossOrigin = 'anonymous'; im.src = x.file; await im.decode(); const W = im.naturalWidth, H = im.naturalHeight, c = chitra.photoMock.render(im, art, { quad: x.quad.map(([a, b2]) => [a * W, b2 * H]), curve: x.curve, opacity: x.opacity, shade: x.shade, blur: x.blur, fit: x.fit }); const t = document.createElement('canvas'); t.width = 360; t.height = Math.round(360 * H / W); t.getContext('2d').drawImage(c, 0, 0, t.width, t.height); res.push({ id: x.id, u: t.toDataURL('image/jpeg', .85), review: x.review }); } catch (e) { res.push({ id: x.id, u: null }); } } return res; });
await p.setContent('<body style="margin:0;padding:10px;background:#ddd;display:flex;flex-wrap:wrap;gap:8px;font:11px system-ui">' + urls.map(x => `<figure style="margin:0;width:360px">${x.u ? `<img src="${x.u}" style="width:360px">` : '<div style="height:200px;background:#fbb">FAILED</div>'}<figcaption>${x.id}${x.review ? ' ⚠ review quad' : ''}</figcaption></figure>`).join('')); await p.waitForTimeout(500); await p.screenshot({ path: out, fullPage: true }); console.log('wrote', out); await b.close();
